version: 0.2

env:
  variables:
    branchname: "git branch | sed"

phases:
  build:
    commands:
    - echo $branchname
    - git branch
    - python helloworld.py
    - branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
    - echo $branch
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
