version: 0.2

env:
  variables:
    branchname: "git branch"
  commands:
    - git branch --column 
phases:
  build:
    commands:
    - ls
    - ls .git/
    - python helloworld.py
    - printenv
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
