version: 0.2

env:
  variables:
    branchname: "git branch"
phases:
  build:
    commands:
    - git branch --column | grep 6ed3e1d177deef88cb01fe4d3ce6560071874d5d
    - pwd
    - git init
    - git branch --column
    - more .git/HEAD
    - echo $CODEBUILD_SOURCE_VERSION
    - echo $CODEBUILD_GIT_BRANCH
    - echo $CODEBUILD_RESOLVED_SOURCE_VERSIONGitHub
    - git branch
    - python helloworld.py
    - printenv
  post_build:
    commands:
    - echo $branchname
    - echo $branchname2
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
