version: 0.2

env:
  variables:
    branchname: "git branch"
  commands:
    - git branch --column 
phases:
  build:
    commands:
    - branch="$(git name-rev --name-only $(git rev-parse HEAD))"
    - echo "${branch}"
    - python helloworld.py
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
  name: myname-$branch
