version: 0.2

env:
  variables:
    branchname: "git branch"
  commands:
    - git branch --column 
phases:
  build:
    commands:
    - echo $CODEBUILD_RESOLVED_SOURCE_VERSIONGitHub
    - pwd
    - git name-rev --name-only $(git rev-parse HEAD)
    - ls
    - ls .git/
    - ls .git/refs/heads
    - more .git/refs/heads/branch3
    - more .git/logs/refs/heads
    - python helloworld.py
    - printenv
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
