version: 0.2
env:
  variables:
    branchname: "git branch | sed -n -e 's/^\* \(.*\)/\1/p'"
phases:
  build:
    commands:
      - python helloworld.py
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
