version: 0.2

env:
  variables:
    branchname: "git branch"
    REPOSITORY_URI: "96337334146.dkr.ecr.eu-west-1.amazonaws.com/hello-world"
phases:
  pre_build:
    commands:
  build:
    commands:
    - python helloworld.py > hello-world
    - aws ecr get-login --no-include-email --region eu-west-1
    - docker build -t hello-world .
    - docker tag hello-world:latest 396337334146.dkr.ecr.eu-west-1.amazonaws.com/hello-world:latest
    - docker push 396337334146.dkr.ecr.eu-west-1.amazonaws.com/hello-world:latest
#- git name-rev --name-only $(git rev-parse HEAD)
    - ls
    - more hello-world
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
  name: MyApp
