version: 0.2

phases:
  build:
    commands:
    - git branch | sed -n -e 's/^\* \(.*\)/\1/p'
    - python helloworld.py
    - git branch | sed -n -e 's/^\* \(.*\)/\1/p'
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
