version: 0.2

env:
  variables:
    branchname: "git branch"
  commands:
    - git branch --column 
phases:
  build:
    commands:
    - git branch
    - git log
    - pwd
    - git cherry-pick 1d1795ba4e43f3501155c7ce3272dd15df674450
    - git init
    - git branch --column
    - more .git/HEAD
    - echo $CODEBUILD_SOURCE_VERSION
    - echo $CODEBUILD_GIT_BRANCH
    - echo $CODEBUILD_RESOLVED_SOURCE_VERSIONGitHub
    - git branch
    - python helloworld.py
    - printenv
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
