version: 0.2

env:
  variables:
    branchname: "git branch"
phases:
  build:
    commands:
    - pwd
    - ls
#- git name-rev --name-only $(git rev-parse HEAD)
    - python helloworld.py > hello-world
    - ls
    - more hello-world
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - Invoke-Expression -Command (Get-ECRLoginCommand -Region eu-west-1).Command
    - docker build -t hello-world .
    - docker tag hello-world:latest 396337334146.dkr.ecr.eu-west-1.amazonaws.com/hello-world:latest
    - docker push 396337334146.dkr.ecr.eu-west-1.amazonaws.com/hello-world:latest
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
