version: 0.2

env:
  variables:
    branchname: "git branch"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=96337334146.dkr.ecr.eu-west-1.amazonaws.com/hello-world
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
    - pwd
    - ls
    - python helloworld.py > hello-world
    - echo Build started on `date`
    - echo Building the Docker image...          
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
#- git name-rev --name-only $(git rev-parse HEAD)
    - ls
    - more hello-world
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - Invoke-Expression -Command (Get-ECRLoginCommand -Region eu-west-1).Command
    - docker build -t hello-world .
    - docker tag hello-world:latest 96337334146.dkr.ecr.eu-west-1.amazonaws.com/hello-world:latest
    - docker push 96337334146.dkr.ecr.eu-west-1.amazonaws.com/hello-world:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - '**/*'
  name: MyApp
