version: 0.2

env:
  variables:
    branchname: "git branch"
phases:
  build:
    commands:
    - pwd
    - git init
    - more .git/HEAD
    - echo $CODEBUILD_SOURCE_VERSION
    - echo $CODEBUILD_GIT_BRANCH
    - echo $CODEBUILD_RESOLVED_SOURCE_VERSIONGitHub
    - git branch
    - python helloworld.py
  post_build:
    commands:
    - echo $branchname
    - echo $branchname2
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
