version: 0.2

env:
  variables:
    branchname: "git branch"
phases:
  build:
    commands:
    - pwd
    - ls
    - git name-rev --name-only $(git rev-parse HEAD)
    - python helloworld.py > MyApp
    - ls
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
